// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package meta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WireObject struct {
	Volatile             *VolatileMeta   `protobuf:"bytes,1,opt,name=Volatile,proto3" json:"Volatile,omitempty"`
	Persistent           *PersistentMeta `protobuf:"bytes,2,opt,name=Persistent,proto3" json:"Persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WireObject) Reset()         { *m = WireObject{} }
func (m *WireObject) String() string { return proto.CompactTextString(m) }
func (*WireObject) ProtoMessage()    {}
func (*WireObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *WireObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireObject.Unmarshal(m, b)
}
func (m *WireObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireObject.Marshal(b, m, deterministic)
}
func (m *WireObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireObject.Merge(m, src)
}
func (m *WireObject) XXX_Size() int {
	return xxx_messageInfo_WireObject.Size(m)
}
func (m *WireObject) XXX_DiscardUnknown() {
	xxx_messageInfo_WireObject.DiscardUnknown(m)
}

var xxx_messageInfo_WireObject proto.InternalMessageInfo

func (m *WireObject) GetVolatile() *VolatileMeta {
	if m != nil {
		return m.Volatile
	}
	return nil
}

func (m *WireObject) GetPersistent() *PersistentMeta {
	if m != nil {
		return m.Persistent
	}
	return nil
}

type VolatileMeta struct {
	Path                 string    `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Show                 string    `protobuf:"bytes,2,opt,name=Show,proto3" json:"Show,omitempty"`
	FileInfo             *FileInfo `protobuf:"bytes,3,opt,name=FileInfo,proto3" json:"FileInfo,omitempty"`
	Parent               string    `protobuf:"bytes,4,opt,name=Parent,proto3" json:"Parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VolatileMeta) Reset()         { *m = VolatileMeta{} }
func (m *VolatileMeta) String() string { return proto.CompactTextString(m) }
func (*VolatileMeta) ProtoMessage()    {}
func (*VolatileMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *VolatileMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolatileMeta.Unmarshal(m, b)
}
func (m *VolatileMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolatileMeta.Marshal(b, m, deterministic)
}
func (m *VolatileMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolatileMeta.Merge(m, src)
}
func (m *VolatileMeta) XXX_Size() int {
	return xxx_messageInfo_VolatileMeta.Size(m)
}
func (m *VolatileMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_VolatileMeta.DiscardUnknown(m)
}

var xxx_messageInfo_VolatileMeta proto.InternalMessageInfo

func (m *VolatileMeta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *VolatileMeta) GetShow() string {
	if m != nil {
		return m.Show
	}
	return ""
}

func (m *VolatileMeta) GetFileInfo() *FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

func (m *VolatileMeta) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type FileInfo struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 int64                `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Mode                 uint32               `protobuf:"varint,3,opt,name=Mode,proto3" json:"Mode,omitempty"`
	ModTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	IsDir                bool                 `protobuf:"varint,5,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileInfo) GetModTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *FileInfo) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type PersistentMeta struct {
	ShowRoot             bool              `protobuf:"varint,1,opt,name=ShowRoot,proto3" json:"ShowRoot,omitempty"`
	Contract             *Contract         `protobuf:"bytes,2,opt,name=Contract,proto3" json:"Contract,omitempty"`
	Instances            []string          `protobuf:"bytes,3,rep,name=Instances,proto3" json:"Instances,omitempty"`
	UserData             map[string]string `protobuf:"bytes,4,rep,name=UserData,proto3" json:"UserData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ImgInfo              *ImgInfo          `protobuf:"bytes,5,opt,name=ImgInfo,proto3" json:"ImgInfo,omitempty"`
	Seq                  *Seq              `protobuf:"bytes,6,opt,name=Seq,proto3" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PersistentMeta) Reset()         { *m = PersistentMeta{} }
func (m *PersistentMeta) String() string { return proto.CompactTextString(m) }
func (*PersistentMeta) ProtoMessage()    {}
func (*PersistentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{3}
}

func (m *PersistentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentMeta.Unmarshal(m, b)
}
func (m *PersistentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentMeta.Marshal(b, m, deterministic)
}
func (m *PersistentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentMeta.Merge(m, src)
}
func (m *PersistentMeta) XXX_Size() int {
	return xxx_messageInfo_PersistentMeta.Size(m)
}
func (m *PersistentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentMeta proto.InternalMessageInfo

func (m *PersistentMeta) GetShowRoot() bool {
	if m != nil {
		return m.ShowRoot
	}
	return false
}

func (m *PersistentMeta) GetContract() *Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *PersistentMeta) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *PersistentMeta) GetUserData() map[string]string {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *PersistentMeta) GetImgInfo() *ImgInfo {
	if m != nil {
		return m.ImgInfo
	}
	return nil
}

func (m *PersistentMeta) GetSeq() *Seq {
	if m != nil {
		return m.Seq
	}
	return nil
}

type Contract struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{4}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type ImgInfo struct {
	Width                int32    `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImgInfo) Reset()         { *m = ImgInfo{} }
func (m *ImgInfo) String() string { return proto.CompactTextString(m) }
func (*ImgInfo) ProtoMessage()    {}
func (*ImgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{5}
}

func (m *ImgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImgInfo.Unmarshal(m, b)
}
func (m *ImgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImgInfo.Marshal(b, m, deterministic)
}
func (m *ImgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImgInfo.Merge(m, src)
}
func (m *ImgInfo) XXX_Size() int {
	return xxx_messageInfo_ImgInfo.Size(m)
}
func (m *ImgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImgInfo proto.InternalMessageInfo

func (m *ImgInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImgInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Seq struct {
	BaseName             string   `protobuf:"bytes,1,opt,name=BaseName,proto3" json:"BaseName,omitempty"`
	First                int32    `protobuf:"varint,2,opt,name=First,proto3" json:"First,omitempty"`
	Last                 int32    `protobuf:"varint,3,opt,name=Last,proto3" json:"Last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seq) Reset()         { *m = Seq{} }
func (m *Seq) String() string { return proto.CompactTextString(m) }
func (*Seq) ProtoMessage()    {}
func (*Seq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{6}
}

func (m *Seq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seq.Unmarshal(m, b)
}
func (m *Seq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seq.Marshal(b, m, deterministic)
}
func (m *Seq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seq.Merge(m, src)
}
func (m *Seq) XXX_Size() int {
	return xxx_messageInfo_Seq.Size(m)
}
func (m *Seq) XXX_DiscardUnknown() {
	xxx_messageInfo_Seq.DiscardUnknown(m)
}

var xxx_messageInfo_Seq proto.InternalMessageInfo

func (m *Seq) GetBaseName() string {
	if m != nil {
		return m.BaseName
	}
	return ""
}

func (m *Seq) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Seq) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type UserArray struct {
	A                    []*UserValue `protobuf:"bytes,1,rep,name=A,proto3" json:"A,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserArray) Reset()         { *m = UserArray{} }
func (m *UserArray) String() string { return proto.CompactTextString(m) }
func (*UserArray) ProtoMessage()    {}
func (*UserArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{7}
}

func (m *UserArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserArray.Unmarshal(m, b)
}
func (m *UserArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserArray.Marshal(b, m, deterministic)
}
func (m *UserArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserArray.Merge(m, src)
}
func (m *UserArray) XXX_Size() int {
	return xxx_messageInfo_UserArray.Size(m)
}
func (m *UserArray) XXX_DiscardUnknown() {
	xxx_messageInfo_UserArray.DiscardUnknown(m)
}

var xxx_messageInfo_UserArray proto.InternalMessageInfo

func (m *UserArray) GetA() []*UserValue {
	if m != nil {
		return m.A
	}
	return nil
}

type UserObject struct {
	O                    map[string]*UserValue `protobuf:"bytes,1,rep,name=O,proto3" json:"O,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserObject) Reset()         { *m = UserObject{} }
func (m *UserObject) String() string { return proto.CompactTextString(m) }
func (*UserObject) ProtoMessage()    {}
func (*UserObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{8}
}

func (m *UserObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserObject.Unmarshal(m, b)
}
func (m *UserObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserObject.Marshal(b, m, deterministic)
}
func (m *UserObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserObject.Merge(m, src)
}
func (m *UserObject) XXX_Size() int {
	return xxx_messageInfo_UserObject.Size(m)
}
func (m *UserObject) XXX_DiscardUnknown() {
	xxx_messageInfo_UserObject.DiscardUnknown(m)
}

var xxx_messageInfo_UserObject proto.InternalMessageInfo

func (m *UserObject) GetO() map[string]*UserValue {
	if m != nil {
		return m.O
	}
	return nil
}

type UserValue struct {
	// Types that are valid to be assigned to Value:
	//	*UserValue_B
	//	*UserValue_N
	//	*UserValue_S
	//	*UserValue_A
	//	*UserValue_O
	Value                isUserValue_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserValue) Reset()         { *m = UserValue{} }
func (m *UserValue) String() string { return proto.CompactTextString(m) }
func (*UserValue) ProtoMessage()    {}
func (*UserValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{9}
}

func (m *UserValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserValue.Unmarshal(m, b)
}
func (m *UserValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserValue.Marshal(b, m, deterministic)
}
func (m *UserValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserValue.Merge(m, src)
}
func (m *UserValue) XXX_Size() int {
	return xxx_messageInfo_UserValue.Size(m)
}
func (m *UserValue) XXX_DiscardUnknown() {
	xxx_messageInfo_UserValue.DiscardUnknown(m)
}

var xxx_messageInfo_UserValue proto.InternalMessageInfo

type isUserValue_Value interface {
	isUserValue_Value()
}

type UserValue_B struct {
	B bool `protobuf:"varint,1,opt,name=B,proto3,oneof"`
}

type UserValue_N struct {
	N float64 `protobuf:"fixed64,2,opt,name=N,proto3,oneof"`
}

type UserValue_S struct {
	S string `protobuf:"bytes,3,opt,name=S,proto3,oneof"`
}

type UserValue_A struct {
	A *UserArray `protobuf:"bytes,4,opt,name=A,proto3,oneof"`
}

type UserValue_O struct {
	O *UserObject `protobuf:"bytes,5,opt,name=O,proto3,oneof"`
}

func (*UserValue_B) isUserValue_Value() {}

func (*UserValue_N) isUserValue_Value() {}

func (*UserValue_S) isUserValue_Value() {}

func (*UserValue_A) isUserValue_Value() {}

func (*UserValue_O) isUserValue_Value() {}

func (m *UserValue) GetValue() isUserValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UserValue) GetB() bool {
	if x, ok := m.GetValue().(*UserValue_B); ok {
		return x.B
	}
	return false
}

func (m *UserValue) GetN() float64 {
	if x, ok := m.GetValue().(*UserValue_N); ok {
		return x.N
	}
	return 0
}

func (m *UserValue) GetS() string {
	if x, ok := m.GetValue().(*UserValue_S); ok {
		return x.S
	}
	return ""
}

func (m *UserValue) GetA() *UserArray {
	if x, ok := m.GetValue().(*UserValue_A); ok {
		return x.A
	}
	return nil
}

func (m *UserValue) GetO() *UserObject {
	if x, ok := m.GetValue().(*UserValue_O); ok {
		return x.O
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserValue_B)(nil),
		(*UserValue_N)(nil),
		(*UserValue_S)(nil),
		(*UserValue_A)(nil),
		(*UserValue_O)(nil),
	}
}

func init() {
	proto.RegisterType((*WireObject)(nil), "meta.WireObject")
	proto.RegisterType((*VolatileMeta)(nil), "meta.VolatileMeta")
	proto.RegisterType((*FileInfo)(nil), "meta.FileInfo")
	proto.RegisterType((*PersistentMeta)(nil), "meta.PersistentMeta")
	proto.RegisterMapType((map[string]string)(nil), "meta.PersistentMeta.UserDataEntry")
	proto.RegisterType((*Contract)(nil), "meta.Contract")
	proto.RegisterType((*ImgInfo)(nil), "meta.ImgInfo")
	proto.RegisterType((*Seq)(nil), "meta.Seq")
	proto.RegisterType((*UserArray)(nil), "meta.UserArray")
	proto.RegisterType((*UserObject)(nil), "meta.UserObject")
	proto.RegisterMapType((map[string]*UserValue)(nil), "meta.UserObject.OEntry")
	proto.RegisterType((*UserValue)(nil), "meta.UserValue")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x6f, 0x4f, 0x13, 0x4f,
	0x10, 0xfe, 0x2d, 0xd7, 0x6b, 0x7b, 0xc3, 0x8f, 0x4a, 0x36, 0x44, 0x2f, 0x55, 0x43, 0x73, 0x91,
	0xd8, 0xf0, 0xe2, 0x48, 0x90, 0x44, 0xa3, 0x89, 0x49, 0x2b, 0x10, 0x1a, 0x85, 0x36, 0x5b, 0x84,
	0xd7, 0x0b, 0x5d, 0xca, 0x69, 0xef, 0x0e, 0xf6, 0x16, 0x0d, 0x7c, 0x01, 0xdf, 0xfb, 0x6d, 0xfc,
	0x76, 0x66, 0x66, 0x6f, 0xaf, 0x85, 0xe0, 0xbb, 0x79, 0xe6, 0xdf, 0x33, 0xf3, 0xec, 0x2c, 0xb4,
	0x52, 0x65, 0xe4, 0x44, 0x1a, 0x19, 0x5f, 0xe9, 0xdc, 0xe4, 0xbc, 0x86, 0xb8, 0xbd, 0x3e, 0xcd,
	0xf3, 0xe9, 0x4c, 0x6d, 0x91, 0xef, 0xec, 0xe6, 0x62, 0xcb, 0x24, 0xa9, 0x2a, 0x8c, 0x4c, 0xaf,
	0x6c, 0x5a, 0xa4, 0x01, 0x4e, 0x13, 0xad, 0x86, 0x67, 0xdf, 0xd4, 0xb9, 0xe1, 0x31, 0x34, 0x4f,
	0xf2, 0x99, 0x34, 0xc9, 0x4c, 0x85, 0xac, 0xc3, 0xba, 0xcb, 0xdb, 0x3c, 0xc6, 0x3e, 0xb1, 0xf3,
	0x1e, 0x2a, 0x23, 0x45, 0x95, 0xc3, 0x77, 0x00, 0x46, 0x4a, 0x17, 0x49, 0x61, 0x54, 0x66, 0xc2,
	0x25, 0xaa, 0x58, 0xb3, 0x15, 0x73, 0x3f, 0xd5, 0x2c, 0xe4, 0x45, 0x77, 0xf0, 0xff, 0x62, 0x3f,
	0xce, 0xa1, 0x36, 0x92, 0xe6, 0x92, 0x18, 0x03, 0x41, 0x36, 0xfa, 0xc6, 0x97, 0xf9, 0x4f, 0xea,
	0x19, 0x08, 0xb2, 0xf9, 0x26, 0x34, 0xf7, 0x93, 0x99, 0x1a, 0x64, 0x17, 0x79, 0xe8, 0x11, 0x57,
	0xcb, 0x72, 0x39, 0xaf, 0xa8, 0xe2, 0xfc, 0x29, 0xd4, 0x47, 0x52, 0xe3, 0x54, 0x35, 0xea, 0x50,
	0xa2, 0xe8, 0x37, 0x9b, 0x37, 0x41, 0x92, 0x23, 0x99, 0x2a, 0x47, 0x8c, 0x36, 0x11, 0x27, 0x77,
	0x8a, 0x88, 0x3d, 0x41, 0x36, 0xfa, 0x0e, 0xf3, 0x89, 0x22, 0xd2, 0x15, 0x41, 0x36, 0xdf, 0x81,
	0xc6, 0x61, 0x3e, 0x39, 0x4e, 0x52, 0x45, 0x0c, 0xcb, 0xdb, 0xed, 0xd8, 0x6a, 0x1d, 0x3b, 0xad,
	0xe3, 0x63, 0xa7, 0xb5, 0x70, 0xa9, 0x7c, 0x0d, 0xfc, 0x41, 0xb1, 0x9b, 0xe8, 0xd0, 0xef, 0xb0,
	0x6e, 0x53, 0x58, 0x10, 0xfd, 0x59, 0x82, 0xd6, 0x7d, 0xbd, 0x78, 0x1b, 0x9a, 0xb8, 0xb3, 0xc8,
	0x73, 0x43, 0xe3, 0x35, 0x45, 0x85, 0x51, 0x87, 0x4f, 0x79, 0x66, 0xb4, 0x3c, 0x77, 0x9a, 0x97,
	0x3a, 0x38, 0xaf, 0xa8, 0xe2, 0xfc, 0x05, 0x04, 0x83, 0xac, 0x30, 0x32, 0x3b, 0x57, 0x45, 0xe8,
	0x75, 0xbc, 0x6e, 0x20, 0xe6, 0x0e, 0xfe, 0x11, 0x9a, 0x5f, 0x0b, 0xa5, 0x77, 0xa5, 0x91, 0x61,
	0xad, 0xe3, 0x75, 0x97, 0xb7, 0xa3, 0xc7, 0x5e, 0x2f, 0x76, 0x49, 0x7b, 0x99, 0xd1, 0xb7, 0xa2,
	0xaa, 0xe1, 0xaf, 0xa1, 0x31, 0x48, 0xa7, 0xf4, 0x20, 0x3e, 0x0d, 0xb2, 0x62, 0xcb, 0x4b, 0xa7,
	0x70, 0x51, 0xfe, 0x1c, 0xbc, 0xb1, 0xba, 0x0e, 0xeb, 0x94, 0x14, 0xd8, 0xa4, 0xb1, 0xba, 0x16,
	0xe8, 0x6d, 0x7f, 0x80, 0x95, 0x7b, 0x04, 0x7c, 0x15, 0xbc, 0xef, 0xea, 0xb6, 0x7c, 0x16, 0x34,
	0x51, 0xb7, 0x1f, 0x72, 0x76, 0xa3, 0xca, 0x7b, 0xb0, 0xe0, 0xfd, 0xd2, 0x3b, 0x16, 0xbd, 0x9a,
	0x8b, 0xc1, 0x43, 0x68, 0x8c, 0xa4, 0x31, 0x4a, 0x67, 0x65, 0xad, 0x83, 0xd1, 0xdb, 0x6a, 0x50,
	0x6c, 0x75, 0x9a, 0x4c, 0xca, 0x73, 0xf3, 0x85, 0x05, 0x78, 0x2f, 0x07, 0x2a, 0x99, 0x5e, 0x5a,
	0x45, 0x7d, 0x51, 0xa2, 0xe8, 0x33, 0x0d, 0x8e, 0xcf, 0xd1, 0x97, 0x85, 0x5a, 0xb8, 0x96, 0x0a,
	0x63, 0xc3, 0xfd, 0x44, 0x17, 0xae, 0xd2, 0x02, 0xbc, 0x99, 0x2f, 0xb2, 0x30, 0x74, 0x33, 0xbe,
	0x20, 0x3b, 0xda, 0x84, 0x00, 0x17, 0xed, 0x69, 0x2d, 0x6f, 0xf9, 0x4b, 0x60, 0xbd, 0x90, 0x91,
	0xe8, 0x4f, 0xac, 0x20, 0x18, 0x3b, 0xc1, 0xc5, 0x04, 0xeb, 0x45, 0x77, 0x00, 0x88, 0xcb, 0x8f,
	0xb9, 0x01, 0x6c, 0x58, 0x26, 0x3f, 0x9b, 0x27, 0xdb, 0x60, 0x3c, 0xb4, 0xcf, 0xc2, 0x86, 0xed,
	0x3d, 0xa8, 0x0f, 0xff, 0x25, 0xe1, 0xc6, 0xa2, 0x84, 0x8f, 0x70, 0x2e, 0x68, 0xfa, 0x8b, 0xd9,
	0x41, 0x29, 0xc0, 0x5b, 0xc0, 0xfa, 0xf6, 0x06, 0x0f, 0xfe, 0x13, 0xac, 0x8f, 0xf8, 0x88, 0x9a,
	0x30, 0xc4, 0x47, 0x88, 0xc7, 0xb4, 0x66, 0x80, 0x78, 0xcc, 0xd7, 0x71, 0xb1, 0xda, 0x43, 0x12,
	0x5a, 0x1a, 0x13, 0x7a, 0xbc, 0x83, 0xcb, 0xd8, 0x7b, 0x59, 0x7d, 0xb8, 0x0c, 0x66, 0x0c, 0xfb,
	0x0d, 0xf0, 0x89, 0xfb, 0xac, 0x4e, 0x9f, 0xe9, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0xb6, 0x34, 0xb7, 0xde, 0x04, 0x00, 0x00,
}
