// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package teflon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersistentMeta struct {
	Proto                string            `protobuf:"bytes,1,opt,name=Proto,proto3" json:"Proto,omitempty"`
	UserData             map[string]string `protobuf:"bytes,2,rep,name=UserData,proto3" json:"UserData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PersistentMeta) Reset()         { *m = PersistentMeta{} }
func (m *PersistentMeta) String() string { return proto.CompactTextString(m) }
func (*PersistentMeta) ProtoMessage()    {}
func (*PersistentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *PersistentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentMeta.Unmarshal(m, b)
}
func (m *PersistentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentMeta.Marshal(b, m, deterministic)
}
func (m *PersistentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentMeta.Merge(m, src)
}
func (m *PersistentMeta) XXX_Size() int {
	return xxx_messageInfo_PersistentMeta.Size(m)
}
func (m *PersistentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentMeta proto.InternalMessageInfo

func (m *PersistentMeta) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *PersistentMeta) GetUserData() map[string]string {
	if m != nil {
		return m.UserData
	}
	return nil
}

func init() {
	proto.RegisterType((*PersistentMeta)(nil), "teflon.PersistentMeta")
	proto.RegisterMapType((map[string]string)(nil), "teflon.PersistentMeta.UserDataEntry")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x49, 0x4d, 0xcb,
	0xc9, 0xcf, 0x53, 0x5a, 0xca, 0xc8, 0xc5, 0x17, 0x90, 0x5a, 0x54, 0x9c, 0x59, 0x5c, 0x92, 0x9a,
	0x57, 0xe2, 0x9b, 0x5a, 0x92, 0x28, 0x24, 0xc2, 0xc5, 0x1a, 0x00, 0x52, 0x23, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x39, 0x70, 0x71, 0x84, 0x16, 0xa7, 0x16, 0xb9, 0x24, 0x96,
	0x24, 0x4a, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xa9, 0xe8, 0x41, 0xcc, 0xd0, 0x43, 0xd5, 0xaf,
	0x07, 0x53, 0xe6, 0x9a, 0x57, 0x52, 0x54, 0x19, 0x04, 0xd7, 0x25, 0x65, 0xcd, 0xc5, 0x8b, 0x22,
	0x25, 0x24, 0xc0, 0xc5, 0x9c, 0x9d, 0x5a, 0x09, 0xb5, 0x06, 0xc4, 0x04, 0x59, 0x5d, 0x96, 0x98,
	0x53, 0x9a, 0x2a, 0xc1, 0x04, 0xb1, 0x1a, 0xcc, 0xb1, 0x62, 0xb2, 0x60, 0x4c, 0x62, 0x03, 0x3b,
	0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xa9, 0x57, 0x78, 0xc8, 0x00, 0x00, 0x00,
}
