// Code generated by pigeon; DO NOT EDIT.

package teflon

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// Convert interface{} to []interface{}
func Isl(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Expr",
			pos:  position{line: 18, col: 1, offset: 200},
			expr: &actionExpr{
				pos: position{line: 18, col: 9, offset: 208},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 18, col: 9, offset: 208},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 18, col: 9, offset: 208},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 18, col: 11, offset: 210},
							label: "ms",
							expr: &zeroOrOneExpr{
								pos: position{line: 18, col: 14, offset: 213},
								expr: &ruleRefExpr{
									pos:  position{line: 18, col: 14, offset: 213},
									name: "MetaSelector",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 18, col: 28, offset: 227},
							label: "os",
							expr: &zeroOrOneExpr{
								pos: position{line: 18, col: 31, offset: 230},
								expr: &ruleRefExpr{
									pos:  position{line: 18, col: 31, offset: 230},
									name: "ObjectSelector",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 18, col: 47, offset: 246},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "ObjectSelector",
			pos:  position{line: 30, col: 1, offset: 442},
			expr: &choiceExpr{
				pos: position{line: 30, col: 19, offset: 460},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 30, col: 19, offset: 460},
						run: (*parser).callonObjectSelector2,
						expr: &seqExpr{
							pos: position{line: 30, col: 19, offset: 460},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 30, col: 19, offset: 460},
									label: "root",
									expr: &zeroOrOneExpr{
										pos: position{line: 30, col: 24, offset: 465},
										expr: &ruleRefExpr{
											pos:  position{line: 30, col: 24, offset: 465},
											name: "AbsPath",
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 30, col: 33, offset: 474},
									label: "ls",
									expr: &oneOrMoreExpr{
										pos: position{line: 30, col: 36, offset: 477},
										expr: &ruleRefExpr{
											pos:  position{line: 30, col: 36, offset: 477},
											name: "Level",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 48, col: 5, offset: 913},
						run: (*parser).callonObjectSelector10,
						expr: &labeledExpr{
							pos:   position{line: 48, col: 5, offset: 913},
							label: "root",
							expr: &ruleRefExpr{
								pos:  position{line: 48, col: 10, offset: 918},
								name: "AbsPath",
							},
						},
					},
				},
			},
		},
		{
			name: "Level",
			pos:  position{line: 52, col: 1, offset: 950},
			expr: &actionExpr{
				pos: position{line: 52, col: 10, offset: 959},
				run: (*parser).callonLevel1,
				expr: &seqExpr{
					pos: position{line: 52, col: 10, offset: 959},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 52, col: 10, offset: 959},
							label: "l",
							expr: &choiceExpr{
								pos: position{line: 52, col: 13, offset: 962},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 52, col: 13, offset: 962},
										name: "RelPath",
									},
									&ruleRefExpr{
										pos:  position{line: 52, col: 23, offset: 972},
										name: "ObjectName",
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 52, col: 35, offset: 984},
							expr: &litMatcher{
								pos:        position{line: 52, col: 35, offset: 984},
								val:        "/",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "AbsPath",
			pos:  position{line: 57, col: 1, offset: 1054},
			expr: &actionExpr{
				pos: position{line: 57, col: 12, offset: 1065},
				run: (*parser).callonAbsPath1,
				expr: &labeledExpr{
					pos:   position{line: 57, col: 12, offset: 1065},
					label: "ss",
					expr: &oneOrMoreExpr{
						pos: position{line: 57, col: 15, offset: 1068},
						expr: &litMatcher{
							pos:        position{line: 57, col: 15, offset: 1068},
							val:        "/",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "RelPath",
			pos:  position{line: 64, col: 1, offset: 1190},
			expr: &actionExpr{
				pos: position{line: 64, col: 12, offset: 1201},
				run: (*parser).callonRelPath1,
				expr: &seqExpr{
					pos: position{line: 64, col: 12, offset: 1201},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 64, col: 12, offset: 1201},
							label: "rr",
							expr: &oneOrMoreExpr{
								pos: position{line: 64, col: 15, offset: 1204},
								expr: &litMatcher{
									pos:        position{line: 64, col: 15, offset: 1204},
									val:        ".",
									ignoreCase: false,
								},
							},
						},
						&andExpr{
							pos: position{line: 64, col: 20, offset: 1209},
							expr: &choiceExpr{
								pos: position{line: 64, col: 22, offset: 1211},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 64, col: 22, offset: 1211},
										val:        "/",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 64, col: 28, offset: 1217},
										name: "EOF",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ObjectName",
			pos:  position{line: 71, col: 1, offset: 1339},
			expr: &actionExpr{
				pos: position{line: 71, col: 15, offset: 1353},
				run: (*parser).callonObjectName1,
				expr: &labeledExpr{
					pos:   position{line: 71, col: 15, offset: 1353},
					label: "fn",
					expr: &oneOrMoreExpr{
						pos: position{line: 71, col: 18, offset: 1356},
						expr: &choiceExpr{
							pos: position{line: 71, col: 20, offset: 1358},
							alternatives: []interface{}{
								&seqExpr{
									pos: position{line: 71, col: 20, offset: 1358},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 71, col: 20, offset: 1358},
											expr: &ruleRefExpr{
												pos:  position{line: 71, col: 21, offset: 1359},
												name: "EscapedChar",
											},
										},
										&charClassMatcher{
											pos:        position{line: 71, col: 33, offset: 1371},
											val:        "[^/]",
											chars:      []rune{'/'},
											ignoreCase: false,
											inverted:   true,
										},
									},
								},
								&seqExpr{
									pos: position{line: 71, col: 40, offset: 1378},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 71, col: 40, offset: 1378},
											val:        "\\",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 71, col: 45, offset: 1383},
											name: "EscapeSequence",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MetaSelector",
			pos:  position{line: 79, col: 1, offset: 1567},
			expr: &actionExpr{
				pos: position{line: 79, col: 17, offset: 1583},
				run: (*parser).callonMetaSelector1,
				expr: &seqExpr{
					pos: position{line: 79, col: 17, offset: 1583},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 79, col: 17, offset: 1583},
							label: "ms",
							expr: &zeroOrOneExpr{
								pos: position{line: 79, col: 20, offset: 1586},
								expr: &ruleRefExpr{
									pos:  position{line: 79, col: 20, offset: 1586},
									name: "Additive",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 79, col: 30, offset: 1596},
							val:        "@",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 34, offset: 1600},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 87, col: 1, offset: 1714},
			expr: &actionExpr{
				pos: position{line: 87, col: 13, offset: 1726},
				run: (*parser).callonAdditive1,
				expr: &seqExpr{
					pos: position{line: 87, col: 13, offset: 1726},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 87, col: 13, offset: 1726},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 87, col: 19, offset: 1732},
								name: "Multiplicative",
							},
						},
						&labeledExpr{
							pos:   position{line: 87, col: 34, offset: 1747},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 87, col: 39, offset: 1752},
								expr: &seqExpr{
									pos: position{line: 87, col: 40, offset: 1753},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 87, col: 40, offset: 1753},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 87, col: 42, offset: 1755},
											name: "AddOp",
										},
										&ruleRefExpr{
											pos:  position{line: 87, col: 48, offset: 1761},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 87, col: 50, offset: 1763},
											name: "Multiplicative",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 67, offset: 1780},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 104, col: 1, offset: 2079},
			expr: &actionExpr{
				pos: position{line: 104, col: 19, offset: 2097},
				run: (*parser).callonMultiplicative1,
				expr: &seqExpr{
					pos: position{line: 104, col: 19, offset: 2097},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 104, col: 19, offset: 2097},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 104, col: 25, offset: 2103},
								name: "Factor",
							},
						},
						&labeledExpr{
							pos:   position{line: 104, col: 32, offset: 2110},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 104, col: 37, offset: 2115},
								expr: &seqExpr{
									pos: position{line: 104, col: 38, offset: 2116},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 104, col: 38, offset: 2116},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 104, col: 40, offset: 2118},
											name: "MulOp",
										},
										&ruleRefExpr{
											pos:  position{line: 104, col: 46, offset: 2124},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 104, col: 48, offset: 2126},
											name: "Factor",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 57, offset: 2135},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Factor",
			pos:  position{line: 121, col: 1, offset: 2434},
			expr: &choiceExpr{
				pos: position{line: 121, col: 11, offset: 2444},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 121, col: 11, offset: 2444},
						run: (*parser).callonFactor2,
						expr: &seqExpr{
							pos: position{line: 121, col: 11, offset: 2444},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 121, col: 11, offset: 2444},
									val:        "(",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 121, col: 15, offset: 2448},
									label: "additive",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 24, offset: 2457},
										name: "Additive",
									},
								},
								&litMatcher{
									pos:        position{line: 121, col: 33, offset: 2466},
									val:        ")",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 123, col: 5, offset: 2501},
						run: (*parser).callonFactor8,
						expr: &labeledExpr{
							pos:   position{line: 123, col: 5, offset: 2501},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 123, col: 11, offset: 2507},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 127, col: 1, offset: 2540},
			expr: &actionExpr{
				pos: position{line: 127, col: 10, offset: 2549},
				run: (*parser).callonValue1,
				expr: &seqExpr{
					pos: position{line: 127, col: 10, offset: 2549},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 127, col: 10, offset: 2549},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 127, col: 15, offset: 2554},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 127, col: 15, offset: 2554},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 127, col: 24, offset: 2563},
										name: "Number",
									},
									&ruleRefExpr{
										pos:  position{line: 127, col: 33, offset: 2572},
										name: "Meta",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 39, offset: 2578},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Meta",
			pos:  position{line: 131, col: 1, offset: 2603},
			expr: &actionExpr{
				pos: position{line: 131, col: 9, offset: 2611},
				run: (*parser).callonMeta1,
				expr: &seqExpr{
					pos: position{line: 131, col: 9, offset: 2611},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 131, col: 9, offset: 2611},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 14, offset: 2616},
								name: "Name",
							},
						},
						&labeledExpr{
							pos:   position{line: 131, col: 19, offset: 2621},
							label: "subs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 131, col: 24, offset: 2626},
								expr: &seqExpr{
									pos: position{line: 131, col: 25, offset: 2627},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 131, col: 25, offset: 2627},
											val:        ".",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 29, offset: 2631},
											name: "Name",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Name",
			pos:  position{line: 141, col: 1, offset: 2821},
			expr: &actionExpr{
				pos: position{line: 141, col: 9, offset: 2829},
				run: (*parser).callonName1,
				expr: &oneOrMoreExpr{
					pos: position{line: 141, col: 9, offset: 2829},
					expr: &charClassMatcher{
						pos:        position{line: 141, col: 9, offset: 2829},
						val:        "[\\pL]",
						classes:    []*unicode.RangeTable{rangeTable("L")},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 145, col: 1, offset: 2870},
			expr: &actionExpr{
				pos: position{line: 145, col: 10, offset: 2881},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 145, col: 10, offset: 2881},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 145, col: 10, offset: 2881},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 145, col: 14, offset: 2885},
							expr: &choiceExpr{
								pos: position{line: 145, col: 16, offset: 2887},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 145, col: 16, offset: 2887},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 145, col: 16, offset: 2887},
												expr: &ruleRefExpr{
													pos:  position{line: 145, col: 17, offset: 2888},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 145, col: 29, offset: 2900,
											},
										},
									},
									&seqExpr{
										pos: position{line: 145, col: 33, offset: 2904},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 145, col: 33, offset: 2904},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 145, col: 38, offset: 2909},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 145, col: 56, offset: 2927},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 151, col: 1, offset: 3099},
			expr: &charClassMatcher{
				pos:        position{line: 151, col: 15, offset: 3115},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 153, col: 1, offset: 3131},
			expr: &choiceExpr{
				pos: position{line: 153, col: 18, offset: 3150},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 153, col: 18, offset: 3150},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 153, col: 37, offset: 3169},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 155, col: 1, offset: 3184},
			expr: &charClassMatcher{
				pos:        position{line: 155, col: 20, offset: 3205},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 157, col: 1, offset: 3218},
			expr: &seqExpr{
				pos: position{line: 157, col: 17, offset: 3236},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 157, col: 17, offset: 3236},
						val:        "u",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 157, col: 21, offset: 3240},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 157, col: 30, offset: 3249},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 157, col: 39, offset: 3258},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 157, col: 48, offset: 3267},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 159, col: 1, offset: 3277},
			expr: &actionExpr{
				pos: position{line: 159, col: 10, offset: 3288},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 159, col: 10, offset: 3288},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 159, col: 10, offset: 3288},
							expr: &litMatcher{
								pos:        position{line: 159, col: 10, offset: 3288},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 15, offset: 3293},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 159, col: 23, offset: 3301},
							expr: &seqExpr{
								pos: position{line: 159, col: 25, offset: 3303},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 159, col: 25, offset: 3303},
										val:        ".",
										ignoreCase: false,
									},
									&oneOrMoreExpr{
										pos: position{line: 159, col: 29, offset: 3307},
										expr: &ruleRefExpr{
											pos:  position{line: 159, col: 29, offset: 3307},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 159, col: 46, offset: 3324},
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 46, offset: 3324},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 166, col: 1, offset: 3520},
			expr: &actionExpr{
				pos: position{line: 166, col: 10, offset: 3529},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 166, col: 12, offset: 3531},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 166, col: 12, offset: 3531},
							val:        "+",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 166, col: 18, offset: 3537},
							val:        "-",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 170, col: 1, offset: 3579},
			expr: &actionExpr{
				pos: position{line: 170, col: 10, offset: 3588},
				run: (*parser).callonMulOp1,
				expr: &choiceExpr{
					pos: position{line: 170, col: 12, offset: 3590},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 170, col: 12, offset: 3590},
							val:        "*",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 170, col: 18, offset: 3596},
							val:        "/",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 174, col: 1, offset: 3638},
			expr: &choiceExpr{
				pos: position{line: 174, col: 11, offset: 3650},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 174, col: 11, offset: 3650},
						val:        "0",
						ignoreCase: false,
					},
					&seqExpr{
						pos: position{line: 174, col: 17, offset: 3656},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 174, col: 17, offset: 3656},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 174, col: 37, offset: 3676},
								expr: &ruleRefExpr{
									pos:  position{line: 174, col: 37, offset: 3676},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 176, col: 1, offset: 3691},
			expr: &seqExpr{
				pos: position{line: 176, col: 12, offset: 3704},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 176, col: 12, offset: 3704},
						val:        "e",
						ignoreCase: true,
					},
					&zeroOrOneExpr{
						pos: position{line: 176, col: 17, offset: 3709},
						expr: &charClassMatcher{
							pos:        position{line: 176, col: 17, offset: 3709},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 176, col: 23, offset: 3715},
						expr: &ruleRefExpr{
							pos:  position{line: 176, col: 23, offset: 3715},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 178, col: 1, offset: 3730},
			expr: &charClassMatcher{
				pos:        position{line: 178, col: 16, offset: 3747},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 180, col: 1, offset: 3754},
			expr: &charClassMatcher{
				pos:        position{line: 180, col: 12, offset: 3767},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 182, col: 1, offset: 3778},
			expr: &charClassMatcher{
				pos:        position{line: 182, col: 23, offset: 3802},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 184, col: 1, offset: 3809},
			expr: &zeroOrMoreExpr{
				pos: position{line: 184, col: 18, offset: 3828},
				expr: &charClassMatcher{
					pos:        position{line: 184, col: 18, offset: 3828},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 186, col: 1, offset: 3840},
			expr: &notExpr{
				pos: position{line: 186, col: 8, offset: 3847},
				expr: &anyMatcher{
					line: 186, col: 9, offset: 3848,
				},
			},
		},
	},
}

func (c *current) onExpr1(ms, os interface{}) (interface{}, error) {
	ex := &Expr{}
	if ms != nil {
		ex.MetaSelector = ms.(ENode)
	}
	if os != nil {
		ex.ObjectSelector = os.(ONode)
	}
	return ex, nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["ms"], stack["os"])
}

func (c *current) onObjectSelector2(root, ls interface{}) (interface{}, error) {
	var rootn ONode
	if root == nil {
		rootn = &RelPath{}
	} else {
		rootn = root.(ONode)
	}
	log.Println("DEBUG: Inside ObjectSelector. Root created:", rootn)
	lsl := Isl(ls)
	firstl := lsl[0].(ONode)
	rootn.SetNext(&firstl)
	for i := 1; i < len(lsl); i++ {
		prev := lsl[i-1].(ONode)
		curr := lsl[i].(ONode)
		prev.SetNext(&curr)
	}
	log.Println("DEBUG: Exiting ObjectSelector.")
	return rootn, nil
}

func (p *parser) callonObjectSelector2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectSelector2(stack["root"], stack["ls"])
}

func (c *current) onObjectSelector10(root interface{}) (interface{}, error) {
	return root, nil
}

func (p *parser) callonObjectSelector10() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectSelector10(stack["root"])
}

func (c *current) onLevel1(l interface{}) (interface{}, error) {
	// log.Println("DEBUG: Inside Level.", l)
	return l, nil
}

func (p *parser) callonLevel1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLevel1(stack["l"])
}

func (c *current) onAbsPath1(ss interface{}) (interface{}, error) {
	log.Println("DEBUG: Inside AbsPath.")
	sssl := Isl(ss)
	ssn := &AbsPath{count: len(sssl)}
	return ssn, nil
}

func (p *parser) callonAbsPath1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAbsPath1(stack["ss"])
}

func (c *current) onRelPath1(rr interface{}) (interface{}, error) {
	log.Println("DEBUG: Inside RelPath.")
	rrsl := Isl(rr)
	rrn := &RelPath{count: len(rrsl)}
	return rrn, nil
}

func (p *parser) callonRelPath1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelPath1(stack["rr"])
}

func (c *current) onObjectName1(fn interface{}) (interface{}, error) {
	log.Println("DEBUG: Inside FileName. fn:", string(c.text))
	onn := NewObjectName(string(c.text))
	return onn, nil
}

func (p *parser) callonObjectName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObjectName1(stack["fn"])
}

func (c *current) onMetaSelector1(ms interface{}) (interface{}, error) {
	log.Println("Inside MetaSelector.")
	if ms == nil {
		return &AllMetaNode{}, nil
	}
	return ms, nil
}

func (p *parser) callonMetaSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMetaSelector1(stack["ms"])
}

func (c *current) onAdditive1(first, rest interface{}) (interface{}, error) {
	n := first.(ENode)
	restSl := Isl(rest)
	for _, v := range restSl {
		vsl := Isl(v)
		op := vsl[1].(string)
		nn := vsl[3].(ENode)
		switch op {
		case "+":
			n = &AddNode{first: n, second: nn}
		case "-":
			n = &SubNode{first: n, second: nn}
		}
	}
	return n, nil
}

func (p *parser) callonAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1(stack["first"], stack["rest"])
}

func (c *current) onMultiplicative1(first, rest interface{}) (interface{}, error) {
	n := first.(ENode)
	restSl := Isl(rest)
	for _, v := range restSl {
		vsl := Isl(v)
		op := vsl[1].(string)
		nn := vsl[3].(ENode)
		switch op {
		case "*":
			n = &MulNode{first: n, second: nn}
		case "/":
			n = &DivNode{first: n, second: nn}
		}
	}
	return n, nil
}

func (p *parser) callonMultiplicative1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1(stack["first"], stack["rest"])
}

func (c *current) onFactor2(additive interface{}) (interface{}, error) {
	return additive, nil
}

func (p *parser) callonFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor2(stack["additive"])
}

func (c *current) onFactor8(value interface{}) (interface{}, error) {
	return value, nil
}

func (p *parser) callonFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor8(stack["value"])
}

func (c *current) onValue1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onMeta1(base, subs interface{}) (interface{}, error) {
	m := &MetaNode{NameList: []string{base.(string)}}
	ssl := Isl(subs)
	for _, v := range ssl {
		s := Isl(v)
		m.NameList = append(m.NameList, s[1].(string))
	}
	return m, nil
}

func (p *parser) callonMeta1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMeta1(stack["base"], stack["subs"])
}

func (c *current) onName1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onName1()
}

func (c *current) onString1() (interface{}, error) {
	// TODO : the forward slash (solidus) is not a valid escape in Go, it will
	// fail if there's one in the string
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onNumber1() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	f, err := strconv.ParseFloat(string(c.text), 64)
	return &NumberNode{Value: f}, err
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onAddOp1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonAddOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1()
}

func (c *current) onMulOp1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonMulOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
