// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package teflon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersistentMeta struct {
	ShowRoot             bool              `protobuf:"varint,1,opt,name=ShowRoot,proto3" json:"ShowRoot,omitempty"`
	Proto                string            `protobuf:"bytes,2,opt,name=Proto,proto3" json:"Proto,omitempty"`
	Instances            []string          `protobuf:"bytes,3,rep,name=Instances,proto3" json:"Instances,omitempty"`
	UserData             map[string]string `protobuf:"bytes,4,rep,name=UserData,proto3" json:"UserData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ImgInfo              *ImgInfo          `protobuf:"bytes,5,opt,name=ImgInfo,proto3" json:"ImgInfo,omitempty"`
	Seq                  *Seq              `protobuf:"bytes,6,opt,name=Seq,proto3" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PersistentMeta) Reset()         { *m = PersistentMeta{} }
func (m *PersistentMeta) String() string { return proto.CompactTextString(m) }
func (*PersistentMeta) ProtoMessage()    {}
func (*PersistentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *PersistentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentMeta.Unmarshal(m, b)
}
func (m *PersistentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentMeta.Marshal(b, m, deterministic)
}
func (m *PersistentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentMeta.Merge(m, src)
}
func (m *PersistentMeta) XXX_Size() int {
	return xxx_messageInfo_PersistentMeta.Size(m)
}
func (m *PersistentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentMeta proto.InternalMessageInfo

func (m *PersistentMeta) GetShowRoot() bool {
	if m != nil {
		return m.ShowRoot
	}
	return false
}

func (m *PersistentMeta) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *PersistentMeta) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *PersistentMeta) GetUserData() map[string]string {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *PersistentMeta) GetImgInfo() *ImgInfo {
	if m != nil {
		return m.ImgInfo
	}
	return nil
}

func (m *PersistentMeta) GetSeq() *Seq {
	if m != nil {
		return m.Seq
	}
	return nil
}

type ImgInfo struct {
	Width                int32    `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImgInfo) Reset()         { *m = ImgInfo{} }
func (m *ImgInfo) String() string { return proto.CompactTextString(m) }
func (*ImgInfo) ProtoMessage()    {}
func (*ImgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *ImgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImgInfo.Unmarshal(m, b)
}
func (m *ImgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImgInfo.Marshal(b, m, deterministic)
}
func (m *ImgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImgInfo.Merge(m, src)
}
func (m *ImgInfo) XXX_Size() int {
	return xxx_messageInfo_ImgInfo.Size(m)
}
func (m *ImgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImgInfo proto.InternalMessageInfo

func (m *ImgInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImgInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Seq struct {
	BaseName             string   `protobuf:"bytes,1,opt,name=BaseName,proto3" json:"BaseName,omitempty"`
	First                int32    `protobuf:"varint,2,opt,name=First,proto3" json:"First,omitempty"`
	Last                 int32    `protobuf:"varint,3,opt,name=Last,proto3" json:"Last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seq) Reset()         { *m = Seq{} }
func (m *Seq) String() string { return proto.CompactTextString(m) }
func (*Seq) ProtoMessage()    {}
func (*Seq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

func (m *Seq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seq.Unmarshal(m, b)
}
func (m *Seq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seq.Marshal(b, m, deterministic)
}
func (m *Seq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seq.Merge(m, src)
}
func (m *Seq) XXX_Size() int {
	return xxx_messageInfo_Seq.Size(m)
}
func (m *Seq) XXX_DiscardUnknown() {
	xxx_messageInfo_Seq.DiscardUnknown(m)
}

var xxx_messageInfo_Seq proto.InternalMessageInfo

func (m *Seq) GetBaseName() string {
	if m != nil {
		return m.BaseName
	}
	return ""
}

func (m *Seq) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Seq) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func init() {
	proto.RegisterType((*PersistentMeta)(nil), "teflon.PersistentMeta")
	proto.RegisterMapType((map[string]string)(nil), "teflon.PersistentMeta.UserDataEntry")
	proto.RegisterType((*ImgInfo)(nil), "teflon.ImgInfo")
	proto.RegisterType((*Seq)(nil), "teflon.Seq")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xe9, 0xba, 0xf6, 0xbb, 0xde, 0xf1, 0x9d, 0x12, 0x44, 0xc2, 0x50, 0x28, 0xc3, 0x87,
	0xfa, 0xd2, 0x87, 0xf9, 0xa0, 0xe8, 0x8b, 0x88, 0x8a, 0xc3, 0x1f, 0x8c, 0x0c, 0xf1, 0x39, 0xba,
	0xbb, 0xad, 0xb8, 0x25, 0xae, 0xb9, 0x2a, 0xfb, 0x93, 0xfc, 0x2f, 0x25, 0x69, 0x53, 0xd9, 0x5b,
	0x3e, 0xa7, 0xe7, 0xe4, 0xdc, 0xdb, 0x40, 0x6f, 0x85, 0x24, 0xa7, 0x92, 0x64, 0xfe, 0x51, 0x6a,
	0xd2, 0x2c, 0x26, 0x9c, 0x2d, 0xb5, 0x1a, 0xfc, 0xb4, 0xa0, 0x37, 0xc6, 0xd2, 0x14, 0x86, 0x50,
	0xd1, 0x23, 0x92, 0x64, 0x7d, 0xe8, 0x4c, 0x16, 0xfa, 0x5b, 0x68, 0x4d, 0x3c, 0x48, 0x83, 0xac,
	0x23, 0x1a, 0x66, 0x7b, 0x10, 0x8d, 0x6d, 0x9e, 0xb7, 0xd2, 0x20, 0x4b, 0x44, 0x05, 0xec, 0x00,
	0x92, 0x91, 0x32, 0x24, 0xd5, 0x1b, 0x1a, 0x1e, 0xa6, 0x61, 0x96, 0x88, 0x3f, 0x81, 0x5d, 0x42,
	0xe7, 0xd9, 0x60, 0x79, 0x2d, 0x49, 0xf2, 0x76, 0x1a, 0x66, 0xdd, 0xe1, 0x51, 0x5e, 0xb5, 0xe7,
	0xdb, 0xcd, 0xb9, 0xb7, 0xdd, 0x28, 0x2a, 0x37, 0xa2, 0x49, 0xb1, 0x63, 0xf8, 0x37, 0x5a, 0xcd,
	0x47, 0x6a, 0xa6, 0x79, 0x94, 0x06, 0x59, 0x77, 0xb8, 0xe3, 0x2f, 0xa8, 0x65, 0xe1, 0xbf, 0xb3,
	0x43, 0x08, 0x27, 0xb8, 0xe6, 0xb1, 0xb3, 0x75, 0xbd, 0x6d, 0x82, 0x6b, 0x61, 0xf5, 0xfe, 0x05,
	0xfc, 0xdf, 0x2a, 0x61, 0xbb, 0x10, 0xbe, 0xe3, 0xc6, 0xed, 0x99, 0x08, 0x7b, 0xb4, 0x2b, 0x7e,
	0xc9, 0xe5, 0x27, 0xfa, 0x15, 0x1d, 0x9c, 0xb7, 0xce, 0x82, 0xc1, 0x69, 0x33, 0x86, 0x35, 0xbd,
	0x14, 0x53, 0x5a, 0xb8, 0x60, 0x24, 0x2a, 0x60, 0xfb, 0x10, 0xdf, 0x61, 0x31, 0x5f, 0x90, 0xcb,
	0x46, 0xa2, 0xa6, 0xc1, 0xbd, 0x1b, 0xca, 0xfe, 0xd8, 0x2b, 0x69, 0xf0, 0x49, 0xae, 0xb0, 0x2e,
	0x6c, 0xd8, 0x5e, 0x78, 0x5b, 0x94, 0xc6, 0x27, 0x2b, 0x60, 0x0c, 0xda, 0x0f, 0xd2, 0x10, 0x0f,
	0x9d, 0xe8, 0xce, 0xaf, 0xb1, 0x7b, 0xc0, 0x93, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0x64,
	0x62, 0x96, 0xd2, 0x01, 0x00, 0x00,
}
