// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package teflon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WireObject struct {
	Volatile             *VolatileMeta   `protobuf:"bytes,1,opt,name=Volatile,proto3" json:"Volatile,omitempty"`
	Persistent           *PersistentMeta `protobuf:"bytes,2,opt,name=Persistent,proto3" json:"Persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WireObject) Reset()         { *m = WireObject{} }
func (m *WireObject) String() string { return proto.CompactTextString(m) }
func (*WireObject) ProtoMessage()    {}
func (*WireObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *WireObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WireObject.Unmarshal(m, b)
}
func (m *WireObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WireObject.Marshal(b, m, deterministic)
}
func (m *WireObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WireObject.Merge(m, src)
}
func (m *WireObject) XXX_Size() int {
	return xxx_messageInfo_WireObject.Size(m)
}
func (m *WireObject) XXX_DiscardUnknown() {
	xxx_messageInfo_WireObject.DiscardUnknown(m)
}

var xxx_messageInfo_WireObject proto.InternalMessageInfo

func (m *WireObject) GetVolatile() *VolatileMeta {
	if m != nil {
		return m.Volatile
	}
	return nil
}

func (m *WireObject) GetPersistent() *PersistentMeta {
	if m != nil {
		return m.Persistent
	}
	return nil
}

type VolatileMeta struct {
	Path                 string    `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Show                 string    `protobuf:"bytes,2,opt,name=Show,proto3" json:"Show,omitempty"`
	FileInfo             *FileInfo `protobuf:"bytes,3,opt,name=FileInfo,proto3" json:"FileInfo,omitempty"`
	Parent               string    `protobuf:"bytes,4,opt,name=Parent,proto3" json:"Parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VolatileMeta) Reset()         { *m = VolatileMeta{} }
func (m *VolatileMeta) String() string { return proto.CompactTextString(m) }
func (*VolatileMeta) ProtoMessage()    {}
func (*VolatileMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *VolatileMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolatileMeta.Unmarshal(m, b)
}
func (m *VolatileMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolatileMeta.Marshal(b, m, deterministic)
}
func (m *VolatileMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolatileMeta.Merge(m, src)
}
func (m *VolatileMeta) XXX_Size() int {
	return xxx_messageInfo_VolatileMeta.Size(m)
}
func (m *VolatileMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_VolatileMeta.DiscardUnknown(m)
}

var xxx_messageInfo_VolatileMeta proto.InternalMessageInfo

func (m *VolatileMeta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *VolatileMeta) GetShow() string {
	if m != nil {
		return m.Show
	}
	return ""
}

func (m *VolatileMeta) GetFileInfo() *FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

func (m *VolatileMeta) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type FileInfo struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 int64                `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Mode                 uint32               `protobuf:"varint,3,opt,name=Mode,proto3" json:"Mode,omitempty"`
	ModTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	IsDir                bool                 `protobuf:"varint,5,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileInfo) GetModTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *FileInfo) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type PersistentMeta struct {
	ShowRoot             bool              `protobuf:"varint,1,opt,name=ShowRoot,proto3" json:"ShowRoot,omitempty"`
	Proto                string            `protobuf:"bytes,2,opt,name=Proto,proto3" json:"Proto,omitempty"`
	Instances            []string          `protobuf:"bytes,3,rep,name=Instances,proto3" json:"Instances,omitempty"`
	UserData             map[string]string `protobuf:"bytes,4,rep,name=UserData,proto3" json:"UserData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ImgInfo              *ImgInfo          `protobuf:"bytes,5,opt,name=ImgInfo,proto3" json:"ImgInfo,omitempty"`
	Seq                  *Seq              `protobuf:"bytes,6,opt,name=Seq,proto3" json:"Seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PersistentMeta) Reset()         { *m = PersistentMeta{} }
func (m *PersistentMeta) String() string { return proto.CompactTextString(m) }
func (*PersistentMeta) ProtoMessage()    {}
func (*PersistentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{3}
}

func (m *PersistentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistentMeta.Unmarshal(m, b)
}
func (m *PersistentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistentMeta.Marshal(b, m, deterministic)
}
func (m *PersistentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistentMeta.Merge(m, src)
}
func (m *PersistentMeta) XXX_Size() int {
	return xxx_messageInfo_PersistentMeta.Size(m)
}
func (m *PersistentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PersistentMeta proto.InternalMessageInfo

func (m *PersistentMeta) GetShowRoot() bool {
	if m != nil {
		return m.ShowRoot
	}
	return false
}

func (m *PersistentMeta) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *PersistentMeta) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *PersistentMeta) GetUserData() map[string]string {
	if m != nil {
		return m.UserData
	}
	return nil
}

func (m *PersistentMeta) GetImgInfo() *ImgInfo {
	if m != nil {
		return m.ImgInfo
	}
	return nil
}

func (m *PersistentMeta) GetSeq() *Seq {
	if m != nil {
		return m.Seq
	}
	return nil
}

type ImgInfo struct {
	Width                int32    `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImgInfo) Reset()         { *m = ImgInfo{} }
func (m *ImgInfo) String() string { return proto.CompactTextString(m) }
func (*ImgInfo) ProtoMessage()    {}
func (*ImgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{4}
}

func (m *ImgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImgInfo.Unmarshal(m, b)
}
func (m *ImgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImgInfo.Marshal(b, m, deterministic)
}
func (m *ImgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImgInfo.Merge(m, src)
}
func (m *ImgInfo) XXX_Size() int {
	return xxx_messageInfo_ImgInfo.Size(m)
}
func (m *ImgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImgInfo proto.InternalMessageInfo

func (m *ImgInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImgInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Seq struct {
	BaseName             string   `protobuf:"bytes,1,opt,name=BaseName,proto3" json:"BaseName,omitempty"`
	First                int32    `protobuf:"varint,2,opt,name=First,proto3" json:"First,omitempty"`
	Last                 int32    `protobuf:"varint,3,opt,name=Last,proto3" json:"Last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seq) Reset()         { *m = Seq{} }
func (m *Seq) String() string { return proto.CompactTextString(m) }
func (*Seq) ProtoMessage()    {}
func (*Seq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{5}
}

func (m *Seq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seq.Unmarshal(m, b)
}
func (m *Seq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seq.Marshal(b, m, deterministic)
}
func (m *Seq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seq.Merge(m, src)
}
func (m *Seq) XXX_Size() int {
	return xxx_messageInfo_Seq.Size(m)
}
func (m *Seq) XXX_DiscardUnknown() {
	xxx_messageInfo_Seq.DiscardUnknown(m)
}

var xxx_messageInfo_Seq proto.InternalMessageInfo

func (m *Seq) GetBaseName() string {
	if m != nil {
		return m.BaseName
	}
	return ""
}

func (m *Seq) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Seq) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func init() {
	proto.RegisterType((*WireObject)(nil), "teflon.WireObject")
	proto.RegisterType((*VolatileMeta)(nil), "teflon.VolatileMeta")
	proto.RegisterType((*FileInfo)(nil), "teflon.FileInfo")
	proto.RegisterType((*PersistentMeta)(nil), "teflon.PersistentMeta")
	proto.RegisterMapType((map[string]string)(nil), "teflon.PersistentMeta.UserDataEntry")
	proto.RegisterType((*ImgInfo)(nil), "teflon.ImgInfo")
	proto.RegisterType((*Seq)(nil), "teflon.Seq")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xd1, 0x6e, 0xd3, 0x40,
	0x10, 0x94, 0xe3, 0x38, 0x75, 0x36, 0xb4, 0x54, 0xa7, 0xaa, 0xb2, 0x22, 0x10, 0x91, 0xc5, 0x43,
	0x90, 0x90, 0x8b, 0x02, 0x02, 0x04, 0x2f, 0x08, 0x95, 0x8a, 0x08, 0x02, 0xd1, 0xa5, 0xd0, 0xe7,
	0x4b, 0xb3, 0x49, 0x0e, 0x6c, 0x5f, 0xeb, 0xbb, 0x16, 0x15, 0xf1, 0x15, 0xfc, 0x05, 0x7f, 0x89,
	0x6e, 0xcf, 0xe7, 0xa4, 0x52, 0xdf, 0x76, 0xc6, 0xb3, 0x33, 0xb7, 0xbb, 0x86, 0xbd, 0x02, 0x8d,
	0x58, 0x08, 0x23, 0xb2, 0x8b, 0x4a, 0x19, 0xc5, 0x3a, 0x06, 0x97, 0xb9, 0x2a, 0xfb, 0x8f, 0x56,
	0x4a, 0xad, 0x72, 0x3c, 0x22, 0x76, 0x7e, 0xb5, 0x3c, 0x32, 0xb2, 0x40, 0x6d, 0x44, 0x71, 0xe1,
	0x84, 0xe9, 0x35, 0xc0, 0x99, 0xac, 0xf0, 0xeb, 0xfc, 0x07, 0x9e, 0x1b, 0xf6, 0x0c, 0xe2, 0xef,
	0x2a, 0x17, 0x46, 0xe6, 0x98, 0x04, 0x83, 0x60, 0xd8, 0x1b, 0x1d, 0x64, 0xce, 0x29, 0xf3, 0xfc,
	0x04, 0x8d, 0xe0, 0x8d, 0x8a, 0xbd, 0x04, 0x98, 0x62, 0xa5, 0xa5, 0x36, 0x58, 0x9a, 0xa4, 0x45,
	0x3d, 0x87, 0xbe, 0x67, 0xf3, 0x85, 0xba, 0xb6, 0x94, 0xe9, 0x1f, 0xb8, 0xb7, 0xed, 0xc8, 0x18,
	0xb4, 0xa7, 0xc2, 0xac, 0x29, 0xb5, 0xcb, 0xa9, 0xb6, 0xdc, 0x6c, 0xad, 0x7e, 0x91, 0x6b, 0x97,
	0x53, 0xcd, 0x9e, 0x42, 0x7c, 0x22, 0x73, 0x1c, 0x97, 0x4b, 0x95, 0x84, 0x94, 0xb6, 0xef, 0xd3,
	0x3c, 0xcf, 0x1b, 0x05, 0x3b, 0x84, 0xce, 0x54, 0x54, 0xf6, 0x65, 0x6d, 0xf2, 0xa8, 0x51, 0xfa,
	0x37, 0xd8, 0xd8, 0xd8, 0x98, 0x2f, 0xa2, 0x40, 0x1f, 0x6d, 0x6b, 0x8a, 0x96, 0xbf, 0x91, 0xa2,
	0x43, 0x4e, 0xb5, 0xe5, 0x26, 0x6a, 0x81, 0x14, 0xbb, 0xcb, 0xa9, 0x66, 0x2f, 0x60, 0x67, 0xa2,
	0x16, 0xa7, 0xb2, 0x40, 0x4a, 0xe8, 0x8d, 0xfa, 0x99, 0xdb, 0x78, 0xe6, 0x37, 0x9e, 0x9d, 0xfa,
	0x8d, 0x73, 0x2f, 0x65, 0x07, 0x10, 0x8d, 0xf5, 0xb1, 0xac, 0x92, 0x68, 0x10, 0x0c, 0x63, 0xee,
	0x40, 0xfa, 0xaf, 0x05, 0x7b, 0xb7, 0x37, 0xc6, 0xfa, 0x10, 0xdb, 0xa9, 0xb9, 0x52, 0x86, 0x9e,
	0x17, 0xf3, 0x06, 0x5b, 0x93, 0xa9, 0xcd, 0xa8, 0xd7, 0xe3, 0x00, 0x7b, 0x00, 0xdd, 0x71, 0xa9,
	0x8d, 0x28, 0xcf, 0x51, 0x27, 0xe1, 0x20, 0x1c, 0x76, 0xf9, 0x86, 0x60, 0xef, 0x20, 0xfe, 0xa6,
	0xb1, 0x3a, 0x16, 0x46, 0x24, 0xed, 0x41, 0x38, 0xec, 0x8d, 0x1e, 0xdf, 0x7d, 0xab, 0xcc, 0xcb,
	0x3e, 0x94, 0xa6, 0xba, 0xe1, 0x4d, 0x17, 0x7b, 0x02, 0x3b, 0xe3, 0x62, 0x45, 0xeb, 0x8f, 0x68,
	0xe0, 0xfb, 0xde, 0xa0, 0xa6, 0xb9, 0xff, 0xce, 0x1e, 0x42, 0x38, 0xc3, 0xcb, 0xa4, 0x43, 0xb2,
	0x9e, 0x97, 0xcd, 0xf0, 0x92, 0x5b, 0xbe, 0xff, 0x16, 0x76, 0x6f, 0x85, 0xb0, 0x7d, 0x08, 0x7f,
	0xe2, 0x4d, 0x7d, 0x06, 0x5b, 0xda, 0x11, 0xaf, 0x45, 0x7e, 0x85, 0x7e, 0x44, 0x02, 0x6f, 0x5a,
	0xaf, 0x83, 0xf4, 0x55, 0xf3, 0x0c, 0x2b, 0x3a, 0x93, 0x8b, 0xfa, 0xd7, 0x89, 0xb8, 0x03, 0xf6,
	0xf2, 0x1f, 0x51, 0xae, 0xd6, 0xee, 0x9f, 0x8c, 0x78, 0x8d, 0xd2, 0x4f, 0xf4, 0x28, 0xbb, 0xd8,
	0xf7, 0x42, 0xe3, 0xd6, 0xdd, 0x1b, 0x6c, 0x0d, 0x4f, 0x64, 0xa5, 0x7d, 0xa7, 0x03, 0xf6, 0xfa,
	0x9f, 0x85, 0x36, 0x74, 0xfd, 0x88, 0x53, 0x3d, 0xef, 0xd0, 0x91, 0x9f, 0xff, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0xee, 0x0b, 0xbe, 0xca, 0x7e, 0x03, 0x00, 0x00,
}
