// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package metadata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserSection struct {
	UserData             map[string]string `protobuf:"bytes,1,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserSection) Reset()         { *m = UserSection{} }
func (m *UserSection) String() string { return proto.CompactTextString(m) }
func (*UserSection) ProtoMessage()    {}
func (*UserSection) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *UserSection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSection.Unmarshal(m, b)
}
func (m *UserSection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSection.Marshal(b, m, deterministic)
}
func (m *UserSection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSection.Merge(m, src)
}
func (m *UserSection) XXX_Size() int {
	return xxx_messageInfo_UserSection.Size(m)
}
func (m *UserSection) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSection.DiscardUnknown(m)
}

var xxx_messageInfo_UserSection proto.InternalMessageInfo

func (m *UserSection) GetUserData() map[string]string {
	if m != nil {
		return m.UserData
	}
	return nil
}

func init() {
	proto.RegisterType((*UserSection)(nil), "metadata.UserSection")
	proto.RegisterMapType((map[string]string)(nil), "metadata.UserSection.UserDataEntry")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x7a,
	0x18, 0xb9, 0xb8, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x53, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x84, 0x1c,
	0xb8, 0x38, 0x4b, 0x8b, 0x53, 0x8b, 0xe2, 0x41, 0x92, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46,
	0xca, 0x7a, 0x70, 0xdd, 0x48, 0x2a, 0xc1, 0x6c, 0x97, 0xc4, 0x92, 0x44, 0xd7, 0xbc, 0x92, 0xa2,
	0xca, 0x20, 0x8e, 0x52, 0x28, 0x57, 0xca, 0x9a, 0x8b, 0x17, 0x45, 0x4a, 0x48, 0x80, 0x8b, 0x39,
	0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x14, 0x12, 0xe1, 0x62, 0x2d,
	0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x49, 0x6c,
	0x60, 0xf7, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x6f, 0x92, 0xcf, 0xb1, 0x00, 0x00,
	0x00,
}
